import * as aspecto from './lore/aspecto';
import * as auxilium from './lore/auxilium';
import * as celeritate from './lore/celeritate';
import * as dixit from './lore/dixit';
import * as doNTimes from './lore/doNTimes';
import * as exmemento from './lore/exmemento';
import * as exsultus from './lore/exsultus';
import * as hic from './lore/hic';
import * as iacta from './lore/iacta';
import * as ianuae from './lore/ianuae';
import * as incendium from './lore/incendium';
import * as infierno from './lore/infierno';
import * as memento from './lore/memento';
import * as noxvida from './lore/noxvida';
import * as radiatum from './lore/radiatum';
import * as random from './lore/random';
import * as satio from './lore/satio';
import * as shakti from './lore/shakti';
import * as stella from './lore/stella';
import * as test123 from './lore/test123';
import * as viburnum from './lore/viburnum';
export declare const description = "The core Magikcraft API spells";
export declare const loreToLoad: (typeof aspecto | typeof auxilium | typeof celeritate | typeof dixit | typeof doNTimes | typeof exmemento | typeof exsultus | typeof hic | typeof iacta | typeof ianuae | typeof incendium | typeof infierno | typeof memento | typeof noxvida | typeof radiatum | typeof random | typeof satio | typeof shakti | typeof stella | typeof test123 | typeof viburnum)[];
