"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.strings = {
    _meta: {
        locale: "en_US"
    },
    APIVERSION: "Magikcraft API version %s loaded",
    AUGURIUM: "Augurium! You create a new augurium!",
    AUXILIUM_PLAYERNAME_404: "Could not find player %s",
    AUXILIUM_PLAYERNAME_REQUIRED: "You must pass a playerName into this funtion, like this: magik.auxilium(playerName);",
    AUXILIUM_SELFHEAL_DISALLOWED: "You cannot heal yourself with this spell!",
    AUXILIUM_SUCCESS_TARGET: "%s healed you!",
    AUXILIUM_SUCCESS: "You healed %s!",
    AUXILIUM_USAGE: "Auxilium! Usage: magik.auxilium(playerName: string) - heal player by playerName. You cannot heal yourself!",
    CALDARIUM_FAIL: "Yummmm, you made a nice soup - but no magik!",
    CALDARIUM_INSUFFICIENT: "There are not enough ingredients!",
    CALDARIUM_NEEDARRAY: "Wrong type of ingredients - I need an array [ ]!",
    CALDARIUM_SPECIFIC: "You produce a new magik word: %s",
    CALDARIUM_TOOMANYINGREDIENTS: "Yuck! Too many ingredients make a terrible soup - and no magik!",
    CALDARIUM_USAGE: "Caldarium! Usage: caldarium(ingredients: string[])",
    CELERITATE: "Celeritate!",
    COLLOCCO: "Collocco!",
    CREO_ALREADY_EXISTS: "The Lore %s already exists!",
    CREO_CREATED: "Created Lore %s",
    DECLARO_MANIFEST: "You manifest one ",
    DECLARO_USAGE: "Declaro! Usage: declaro(item: string) - Manifest the <item>.",
    DECLARO: "Declaro!",
    EICERE_GENERIC: "Your rider has been ejected",
    EICERE_NOTFOUND: "There was no one to eject",
    EICERE_USAGE: "You eject the person on your back!",
    EICERE: "Eicere!",
    EXSULTO_USAGE: "Exsulto! Usage: exsulto(power: number)",
    EXSULTUS_GENERIC: "You jump with some power!",
    EXSULTUS_SPECIFIC: "You jump with a power of %s%",
    EXSULTUS_USAGE: "Exsultus! Usage: exsultus(power: number) - Jump you in the air.",
    EXSULTUS: "Exsultus!",
    FULMEN_GENERIC: "You call down lightning on this plane!",
    HIC_USAGE: "Usage: hic() - Returns your current location.",
    IACTA_FAIL: " tried to toss you!",
    IACTA_INFORM: " tossed you!",
    IACTA_NOTFOUND: "I can't find ",
    IACTA_REBOUND: "Your spell rebounds!",
    IACTA_SELF: "You tossed yourself!",
    IACTA_SPECIFIC: "You tossed ",
    IACTA_USAGE: "Iacta! Usage: iacta(playername: string)",
    IACTA: "Iacta! You throw someone!",
    IANUAE_GENERIC: "You teleport somewhere!",
    IANUAE_USAGE: "Usage: ianuae(location:vector) - Teleport you to location.",
    IANUAE: "Ianuae!",
    IGNIFERA_GENERIC: "You cast a fireball!",
    ILLIC_USAGE: "Returns the location where you are looking",
    INCANTA_SPECIFIC: "Incanta! ",
    INCANTA: "Incanta! You enchant someone!",
    INCENDIUM_GENERIC: "You light someone on fire!",
    INCENDIUM_INFORM: " set you on fire!",
    INCENDIUM_NOTFOUND: "Could not find ",
    INCENDIUM_SELF: "You set yourself on fire!",
    INCENDIUM_SPECIFIC: "You set fire to ",
    INCENDIUM_USAGE: "Incendium! Usage: incendium(playername: string) - Set <playername> on fire.",
    INCENDIUM: "Incendium!",
    INTERPOLATIONTEST: "Interpolate %s",
    INTERPOLATIONTEST2: "Interpolate %s and %s",
    LIGABISUIRGAE_SPECIFIC: "Ligabis! You bound a spell to your wand!",
    LIGABISUIRGAE_USAGE: "Usage: ligabisuirgae(spell) - bind spell to wand",
    LIGABISUIRGAE: "Ligabis!",
    MEMENTO_NOTHING: "Nothing to remember!",
    MEMENTO_PLACE: "I remembered this place",
    MEMENTO_SPECIFIC: "Remembered: ",
    MEMENTO_USAGE: "Memento! Remember a thing. Usage: magik.memento(thing);",
    MEMORIAE: "Remembered: ",
    PERSCRIBO_CREATED: "Created spell: magik.Lore.%s.%s",
    PERSCRIBO_DOESNT_EXIST: "This Lore doesn't exist! Name: ",
    PERSCRIBO_NAMED_SPELL: "The spell must be a named function - eg: function storm(){}",
    PERSCRIBO_SPELL_EXISTS: "This spell already exists in this Lore. Name: ",
    PERSCRIBO_USAGE: "Perscribo! Usage: perscribo(lore: string, spell: function)",
    PRESS_T_CLICKLINK: "Press 'T' and click the link below:",
    RADIATUM_GENERIC: "You make someone radioactive!",
    RADIATUM_INFORM: " makes you radioactive!",
    RADIATUM_OFF_INFORM: " takes away your glow",
    RADIATUM_OFF_SELF: "You de-radioactivate youself",
    RADIATUM_OFF_SPECIFIC: "You de-radioactivate ",
    RADIATUM_SELF: "You made yourself radioactive!",
    RADIATUM_SPECIFIC: "You radioactivate ",
    RADIATUM_USAGE: "Radiatum! Usage: radiatum(playername: string)",
    RADIATUM: "Radiatum!",
    SATIO_GENERIC: "Satisfy your hunger with magik!",
    SATIO_USAGE: "You satisfied your hunger with magik!"
};
